---
abstract: 'Merge two nested data structures, with merging modes and options'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
generated_by: 'Dist::Zilla version 2.101241'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-ModeMerge
recommends: {}
requires:
  Any::Moose: 0
  Clone: 0
  Clone::Any: 0
  Mouse: 0
  Test::Aggregate: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/perl-Data-ModeMerge/
  repository: http://github.com/sharyanto/perl-Data-ModeMerge
version: 0.24
