---
abstract: 'Merge two nested data structures, with merging modes and options'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Test::Exception: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-ModeMerge
requires:
  Log::Any: 0
  Moo: 0
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Data-ModeMerge/
  repository: http://github.com/sharyanto/perl-Data-ModeMerge
version: 0.30
